### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by vwilburn**
- "Front Door" is an internal only name. 
- guestbook-frontdoor.yaml is not in the repo
- Removed list of features since they change too often and linked to docs that are constantly updated. 
- Took a guess at what the point of talking about Front Door after doing the Istio Ingress setup. Is this new annotation what you're doing here? https://console.bluemix.net/docs/containers/cs_annotations.html#istio-annotations
- Updated titles to reflect user benefit of the tasks.

### CODE REVIEW

**Comment by szihai** [comment]
Front door  is a feature offered by Armada. It is not part of Istio and has no dependencies on Istio. In the original workshop : https://github.com/szihai/istio-workshop/tree/indexsf/exercise-12,
we were relaying traffic from Front door ingress to Istio ingress. But in this version, there is no such relationship, which raise the question of "do we need it ?".
The yaml file is there in the guestbook-go directory.

**Comment by linsun** [comment]
Could we have front door as an optional portion in the exercise/module?  I think that will be good so that users with free cluster can skip and paid cluster can learn.

**Comment by vwilburn** [comment]
@szihai Per Doug in Slack course-containers, that yaml should go to: https://github.com/IBM/guestbook

**Comment by vwilburn** [comment]
oops, hit enter to quickly.
he also said: "IMO nothing new should be going there."

**Comment by nilesh32** [comment]
I agree with Lin. Let's make Frontdoor an optional module it's only available on paid clusters. To Vanessa's point, Frontdoor's customer-facing name should be Ingress Controller. Not to confuse with Istio Ingress, maybe we can call it IBM Ingress Controller?

**Comment by linsun** [comment]
@szihai Could you submit a PR?   @szihai can you help review this one for me?

**Comment by vwilburn** [comment]
Since several items were rolled up in this PR, please do a subsequent PR to address any issues with the relationship of Istio Ingress versus ICCS Kubernetes ALB ingress (frontdoor).

**Pull request merged**
