### PR TITLE
Add Kiali install and config to exec4

### PR DESCRIPTION
**Pull request by emmayang**
Kiali is another very powerful tool to observe service mesh, and will be included in default Istio offering in next 1.1 release. 

Added installation and configuration details for Kiali, so users can leverage its all functionalities as well.

### CODE REVIEW

**Comment by emmayang** [comment]
Thanks @linsun for your review, and sorry for the late response... 
I checked with Iris, and she confirmed the demo environment will use Istio 1.0, and will not use preliminary 1.1, so to be safe we used non-helm way to install it. And I did met some problem when using helm to enable Kiali, and opened an issue in their repo.

**Comment by linsun** [comment]
@emmayang and @irisdingbj if you need Kiali to be installed using non-helm way, pls fork this repo for your lab.  I would prefer to use helm to install Kiali and fix the issue you mentioned in 1.1.   Could you link the issue here?

**Comment by emmayang** [comment]
@linsun sure, thanks. And here's the issue I opened https://github.com/kiali/kiali/issues/644.

**Comment by emmayang** [comment]
And according to Kiali guys, fix already merged in Istio repo, and waiting for latest release. I will close this PR for now, and refine the doc later after the all fixed and tested. Thanks again Lin @linsun .

**Pull request closed without merging**
