### PR TITLE
Updates for Exercise 4 and 5

### PR DESCRIPTION
**Pull request by Nadine2016**

### CODE REVIEW

**Comment by linsun** [comment]
@szihai can you review this?

**Comment by szihai** [comment]
Yeah, since the master has changed both need to resolve conflicts. Otherwise they look good.

**Comment by linsun** [comment]
@Nadine2016 can you resolve the conflict?  I'll merge after that.

**Comment by Nadine2016** [comment]
@linsun @szihai merge conflicts are resolved. I do not have write access to merge. can you please do it?

**Pull request merged**
